// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAagEEjI06wt8BzZe7v6j37rOrPJMCphdA',
    appId: '1:253620356691:web:05de0d59915dfa4346a8a6',
    messagingSenderId: '253620356691',
    projectId: 'recipe-aa942',
    authDomain: 'recipe-aa942.firebaseapp.com',
    storageBucket: 'recipe-aa942.appspot.com',
    measurementId: 'G-E6CR83Q79J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIATywfeVsRODN36WC2ex6OZ8Y6-IZds',
    appId: '1:253620356691:android:fd0dc8b7793fef2146a8a6',
    messagingSenderId: '253620356691',
    projectId: 'recipe-aa942',
    storageBucket: 'recipe-aa942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2af0L81ScFo-q_9m0yjsTW6q78kmH7iY',
    appId: '1:253620356691:ios:9496c841a95c4ce446a8a6',
    messagingSenderId: '253620356691',
    projectId: 'recipe-aa942',
    storageBucket: 'recipe-aa942.appspot.com',
    iosClientId: '253620356691-i0oh5po0l0909mpum3587oanmim8m44r.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeSuggestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2af0L81ScFo-q_9m0yjsTW6q78kmH7iY',
    appId: '1:253620356691:ios:9496c841a95c4ce446a8a6',
    messagingSenderId: '253620356691',
    projectId: 'recipe-aa942',
    storageBucket: 'recipe-aa942.appspot.com',
    iosClientId: '253620356691-i0oh5po0l0909mpum3587oanmim8m44r.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeSuggestion',
  );
}
